CREATE TABLE `authors` ( 
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT , 
  `name` VARCHAR(255) NOT NULL , 
  `short_bio` VARCHAR(255) NOT NULL , 
  `birth_date` DATE NULL , 
  `death_date` DATE NULL , 
  PRIMARY KEY (`id`)
) ENGINE = InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci;

('James J. Farrell'),
('Maxwell Shane'),
('Evan Esar'),
('Jared Call'),
('unknown'),
('Ambrose Bierce'),
('Samuel Johnson'),
('Ambrose Bierce *'),
('Matthew Wren'),
('Leonard L. Levinson'),
('Italian Proverb'),
('Philip Sidney'),
('Miguel de Cervantes'),
('Addison Mizner'),
('G.W.F. Hegel'),
('Plato'),
('Al Boliska'),
('Jean-Jacques Rousseau'),
('Salada Tea'),
('Joseph Pulitzer'),
('Adlai Stevenson'),
('Charles Simmons'),
('Zeke Canova'),
('Quincy'),
('Robert J. Landry'),
('Norman Ferraci'),
('George Flewelling, Nashua, N.H.'),
('George Moore'),
('Walter Mathau'),
('Alfred Lunt'),
('Nikos Kazantzakis'),
('N'),
('Ferdinand Foch'),
('Dr. Jesperson'),
('Clausewitz'),
('Vic Fredericks'),
('H.L. Mencken'),
('Lawrence Barrett; Edwin Booth'),
('Morton Thompson'),
('Michael Wilding'),
('William Hazlitt'),
('Joan Littlewood'),
('Paula Victor'),
('Tailspinner'),
('Mark Twain'),
('Alexander Woollcott'),
('Norbert Nadel'),
('Francis Grose'),
('Michael Ramsey'),
('Josh Billings'),
('Joseph Addison'),
('Benjamin Franklin'),
('James B. Applegate, Jr.'),
('Cy N. Peace'),
('Joyce Armor'),
('Dan Bennett'),
('Marcelene Cos'),
('Wayne Hammond, New Waverly, TX'),
('A.S. Neil'),
('Holbrook Jackson'),
('Bernard Shaw'),
('Jim Backus'),
('Pep Mealiffe'),
('Gene Autry'),
('Gilbert Keith Chesterton'),
('Herbert Spencer Dickey'),
('William Bolitho'),
('English Proverb'),
('Justin McCarthy'),
('Robert Leighton'),
('Samual Johnson'),
('Edmunt Burke'),
('Lord Byron'),
('Thomas Jefferson'),
('James R. Adams'),
('Chester L. Posey'),
('Bernard DeVoto'),
('F. Scott Fitzgerald'),
('Stephen Lealock'),
('Fred Allen'),
('Judge'),
('Charles Caleb Colton'),
('Jane Hunt Clark'),
('Bill Manville'),
('Chambers'),
('J.C. Salak'),
('Tom Stoppard'),
('Paul and Helen Martin Denix'),
('Robert Lembke'),
('Arthur Radford'),
('Hoffman Nickerson'),
('Winston Churchill'),
('Clifton Fadiman'),
('Raymond Haggard'),
('Shelly Berman'),
('Oliver Herford'),
('Sen. Lyndon Johnson'),
('Dylan Thomas'),
('Bobby Hedge, Roanoke, VA'),
('Lewis Carroll'),
('Walter McDonald'),
('Herb Shriner'),
('Walter Slezak'),
('Authur Murray\'s press agent'),
('Arthur \"Bugs\" Baer'),
('Al Bernie'),
('Elise Bratis'),
('Charles Haddon Spurgeon'),
('Jimmy Cannon'),
('Roger Kahn'),
('Sir Henry Wotton'),
('Oscar Wilde'),
('Bruce Lefler'),
('Dick Rattazi'),
('Will Rogers'),
('John Barrymore'),
('Colonel F.F. Parry, USMC'),
('French Proverb'),
('Ned Bruce, Shorewood, Minn.'),
('Shay Adkins, Battle Creek, Mich.'),
('Robert Graves, 1929'),
('James J Farrell'),
('R.L. Gledhill'),
('Oliver Wendell Holmes [1809-94]'),
('H.L. Menken'),
('Michael H. Burnham'),
('Jonathan Swift'),
('Bill Gold'),
('AndrŽ Gide'),
('Twyla Tharp'),
('George Bernard Shaw'),
('Fulton J. Sheen'),
('Robert Orben'),
('Roger Rosenblatt'),
('Baron de Montesquieu'),
('Sinclair Lewis'),
('Mrs. Judy O\'Reilly'),
('Ronald Reagan'),
('Nick LaPole'),
('Colette'),
('Ken Kraft'),
('Russell Newbold'),
('Ogden Nash'),
('Mannie Manheim'),
('Larry Matthews\' press agent.'),
('Frank J. Pepe'),
('Henna Arond Zacks'),
('Ed Wynn'),
('Harry Toffel'),
('Al Cooper\'s press agent'),
('Cosmo Sardo'),
('Joe Ryan'),
('Douglas Jerrold'),
('Senator Soaper'),
('Bert Kruse'),
('Alain'),
('Oscar Levant'),
('Elizabeth Taylor'),
('Balzac'),
('AndrŽ Maurois'),
('Talitha Botsford'),
('Robert Frost'),
('Hal Raymond'),
('Adapted from Bernard Shaw'),
('Jack Kraus'),
('Nicholas Roosevelt'),
('Dr. Samuel Jounson'),
('Albert Einstein'),
('Johnny Hart'),
('Burton Hillis'),
('W. Somerset Maugham'),
('HonorŽ de Balzac'),
('Pascal'),
('Ambrose Pierce'),
('Kevin Gunning, Hale, Mich.'),
('Helen Daley'),
('Shalimar'),
('George Orwell'),
('Chauncey Depew'),
('Sydney Smith'),
('Mencius'),
('Paul and Helen Marin Denis'),
('Bertha Shore'),
('Llewellyn Miller'),
('Lewis Gillenson'),
('Jim Chesebro, Corona del Mar, Calif.'),
('Philip Guedalla'),
('John Arbuthnot'),
('William Wordsworth'),
('Izaak Walton'),
('James Montgomery Bailey'),
('Reported by Robert P. Sutton'),
('Samuel Butler'),
('Thomas A. Edison'),
('Mort Sahl'),
('Charles Lamb'),
('Bob Lewis'),
('Victor Hugo'),
('Bert Leston Taylor'),
('Gian Vincezo Lavina'),
('Melville D. Landon'),
('Frank Tyger'),
('Jackie Kannon'),
('Countess of Blessington'),
('John D. MacDonald'),
('Adlai Stenenson'),
('The Proper Bostonians'),
('Cleveland Amory'),
('Lucius Beebe'),
('Ex. Gov. Ellis Arnall of Georgia'),
('T.S. Eliot'),
('Charles Francis Adams II'),
('Margaret Shavers'),
('Florence Marley'),
('Russian Proverb'),
('Leo P. Driessen'),
('William V. Shannon'),
('Judith Viorst'),
('Dorothy Parker'),
('William Shakespeare'),
('Bill Manvile'),
('English doctor'),
('Nye Bevan'),
('G.K. Chesterton'),
('Nicky Blair'),
('Elizabethan meaning'),
('Heywood Hale Broun'),
('F.G. Kernan or A. Latimer'),
('Les and Liz Carpenter'),
('Lyda Fairbanks'),
('St. Augustine'),
('Andr_ Maurois'),
('Stuart Chase'),
('Alexandre Dumas the Younger'),
('Judith Beach'),
('Jack Herbert'),
('Herbert V. Prochnow'),
('unknown *'),
('Batiuk'),
('N.T. Cosby, Middletown, Ill.'),
('Johnathan Swift'),
('Richard Steele'),
('Anatole France'),
('Dwight L. Moody'),
('Elbert Hubbard'),
('Bill Vaugham'),
('Dinah Maria Mulock'),
('Henri Frédéric Amiel'),
('Ovid'),
('John W. Whitehead'),
('Henry W. Nevinson'),
('Ernest Hemmingway'),
('Louis I. Kahn'),
('Sigmund Freud'),
('Matthew Wall'),
('Sid Ascher'),
('Ron Mahlo, Garland, TX'),
('Bill Granger'),
('Steve Sommer'),
('Herb Schmertz'),
('Frank A. Clark'),
('Robert Fitch'),
('Milton Berle'),
('James J. Farrell *'),
('E.B. White'),
('Mark Meggison, China Grove, N.C.'),
('Ralph Waldo Emerson'),
('John Steinbeck'),
('Gallhager(sp?)'),
('Edith Ogutsch'),
('Bert Murray'),
('Allison Sanders'),
('Woodrow Wilson'),
('Franklin Delano Roosevelt'),
('Pindar'),
('Don Herold'),
('Andy Gates, Shippensburg, PA'),
('John Wayne'),
('Charles Maurice de Tallyrand'),
('Eugene T. Maleska'),
('Robert Kelly'),
('Charles Dickens'),
('Doug Larson'),
('Channing Pollock'),
('James Gibbons Huneker'),
('Benjamin Disraeli'),
('Ivan Shrewsbury Cobb'),
('Lakenan Barnes'),
('Paul H. Gilbert'),
('Raymond J. Cvikota'),
('S. Leonard Rubinstein'),
('Tony Zarro'),
('Theodore Parker'),
('Walt Cherry, Orangeburg, S.C.'),
('John Beliveau, Aiken, S.C.'),
('Arthur Garfield Hays'),
('Clark Smith'),
('Ralph Noel'),
('G. Brian Daly'),
('Percy Verance'),
('Isaac Goldberg'),
('Charlotte Rubsamen'),
('Brett Vribe, Sun Valley, Cal.'),
('Gloria M. Schlesna'),
('S. Potter'),
('Richard Vecker'),
('M. Randisi'),
('Austin O\'Malley'),
('Alexandre (pŽre) Dumas'),
('Anthony Hope'),
('Wallace Sterling'),
('George Horace Lorimer'),
('George Savile, (Marquis of) Halifax'),
('Malcolm S. Forbes'),
('Friedrich Wilhelm Nietzsche'),
('Amthony Ratcliffe, Royal Oak, Mich.'),
('Norman Ferrari'),
('Euripides'),
('Edward Robert Bulwer-Lytton'),
('Lionel Strachey'),
('Shailer Mathews'),
('Irvin Shrewsbury Cobb'),
('Arnold H. Glasow'),
('Earl Wilson'),
('James Dent'),
('Kahlil Gigran'),
('Austen O\'Malley'),
('Nicholas Murray Butler'),
('Henry Wadsworth Longfellow'),
('Pierre Corneille'),
('Cicero'),
('Tobias Smollett'),
('Henry Ford'),
('Sherwood Eddy'),
('William Adams'),
('St Augustine'),
('Thomas Aquinas'),
('St. Paul'),
('Martin Luther'),
('D.S. Muzzey'),
('Leo Tolstoy'),
('Nicholas Chamfort'),
('Socrates'),
('Toledo Blade'),
('Ouida'),
('Alexander Pope'),
('Marge Piercy'),
('Bill Cosby'),
('Arthur Wing Pinero'),
('Babs Z. DiBacco'),
('Don Marquis'),
('George Sand'),
('Al Bernstein'),
('Max O\'Rell'),
('Henry Ward Beecher'),
('Jean de la BruyŽre'),
('Hopkinton, Iowa Leader'),
('Len Elliott'),
('Lance Morrow'),
('Larry Eisenburg'),
('Jane Adams'),
('Eustache Deschamps'),
('Edwin Arlington'),
('Tom Wilson'),
('Paul Greeley, Jr.'),
('E.H. Chapin'),
('Francois de La Rochefoucauld'),
('Dutch Proverb'),
('William Inge'),
('Etienne Bonnot, AbbŽ de Condillac'),
('Stephen Potter'),
('Francis Bacon'),
('Charles J. Connor, Jr'),
('Aldous Huxley'),
('Nathaniel Hawthorne'),
('Will Henry'),
('Bernard Berenson'),
('Edmund de Goncourt'),
('Nietzsche'),
('Thomas Alva Edison'),
('Buffon, attributed'),
('Willian James'),
('W. H. Auden'),
('Samuel Butler [1835-1902]'),
('V. S. Pritchett'),
('Jane Ellice Hopkins'),
('Clive Bell'),
('Edward S. Herman'),
('Marshall McLuhan'),
('John Ciardi'),
('Cardinal Newman'),
('Fresno, CA, Bee'),
('John Ruskin'),
('Larry Cohen, Steve Zweig'),
('Joseph Goebbels'),
('Langston Hughes'),
('Issac Goldberg'),
('Sene\'n Guillermo Moll_da'),
('Isak Dineson'),
('N.B. Guyol'),
('Jean Giraudoux'),
('Gina Lollobrigida'),
('Lesage'),
('Peter de Vries'),
('Spinoza'),
('Jean Paul Richter'),
('William Watson'),
('St. John of Damascus'),
('Nietzche'),
('Herbert Beerbohm Tree'),
('Plato, attributed'),
('St. Anselm'),
('Gerard Manley Hopkins'),
('Emerson'),
('Robert Browning'),
('Frederick Fell'),
('O. K. Bovard'),
('B. C. Forbes'),
('Leigh Montville'),
('Aristotle'),
('Horatio Smith'),
('Herbert A. Kenny'),
('Joe Paul, Jr.'),
('La Rochefoucauld'),
('J.B. Massieu'),
('Hosea Ballou'),
('Steven Fox'),
('Pat Napolitano'),
('Fredric Whitaker'),
('Lois Sutton'),
('Jean Jacques Rousseau'),
('Eleanor Roosevelt'),
('E.L. Konigsburg'),
('Charles M. Schulz'),
('Logan MacDowell'),
('Egyptian Proverb'),
('Oliver Wendell Holmes'),
('Tim Spellman'),
('David Dorman'),
('Alan Patrick Herbert'),
('Brander Mathews'),
('August Wilhelm von Schlugel'),
('Graham Swift'),
('V. Tubazio'),
('Robert Green Ingersoll'),
('Emily Dickinson'),
('Benjamin De Casseres'),
('E.D. Hulse'),
('Helen Rowland'),
('Oliver Wendell Holmes, Jr'),
('John H. Dromey'),
('Philip Wylie'),
('George Scialabba'),
('Robertson Davies'),
('Henry David Thoreau'),
('Hank Billings'),
('Frank Huges'),
('Christopher Morley'),
('Johin Biebold'),
('Nick Lavidor'),
('John Irwin, Elyria, Ohio'),
('Julian Brown'),
('Ann Black'),
('Martin Farquhar Tupper'),
('Rick Ruggles, West Union , Ohio'),
('John Pentland Mahaffy'),
('Ronn Brackin'),
('Winthrop Sargeant'),
('Paul Whitman'),
('George Gershwin'),
('William Shenstone'),
('J.C.F. Schiller'),
('Robert Louis Stevenson'),
('John Keats'),
('LaRochefoucauld'),
('Mme. de Puisieux'),
('Joe Golicic'),
('Adela Rogers St. Johns'),
('Alphonse Lamartine'),
('Henri-FrŽdŽric Amiel'),
('Jeremy Bentham'),
('Martial'),
('Ramond J. Cvikota'),
('Betsy Deter'),
('Frances Peterson'),
('Helen Keller'),
('Karl W. Humboldt'),
('James Henry'),
('Pierre Charles Baudelaire'),
('Thomas H. Huxley'),
('Danny Kaye'),
('John Bradbury'),
('\'Madame\''),
('Magnus Hirschfeld'),
('Baron Lytton'),
('Paul Geraldy'),
('June Masters Bacher'),
('Sappho'),
('Han Suyin'),
('James Alexander Thom'),
('Branch Rickey'),
('Jayne Mansfield'),
('Mathew Wall'),
('William Schwenck Gilbert'),
('Phyllis McGinley'),
('Andre Maurois'),
('Ian Hay'),
('Herbert Spencer'),
('Beverley Nichols'),
('Christina of Sweden'),
('James Bryce'),
('Corrie ten Boom with John and Elizabeth Sherrill'),
('Joyce Hall'),
('Pat Douslin'),
('Richard Armour'),
('Henry Fielding'),
('Winston Mizner'),
('John Naisbitt'),
('Scott Briggs'),
('G.W. Croft'),
('Dante Mancini, North Canton, OH'),
('Michelle Crapo, Bothell, Wash'),
('Olaf Stapledon'),
('Richard Arlington'),
('Dante'),
('William Pitt'),
('HondrŽ de Balzac'),
('Herbert Casson'),
('Dr. Carl Jung'),
('Louis Kossuth'),
('Ernest Boyd'),
('ascribed to John Bogart'),
('Edgar Watson Howe'),
('George Washburn'),
('John Macy'),
('James Ellis'),
('Arthur Baer'),
('Baltimore Sun Motto'),
('Pennsylvania Gazette'),
('John Florio'),
('J.W. von Goethe'),
('Zach Kelton, Studio City, Cal'),
('Michel de Montaigne'),
('Leigh Hunt'),
('Mike Fuller, San Antonio, TX'),
('Greg Bucking, Sag Harbor, NY'),
('Homer'),
('Lord (4th Earl of) Chesterfield'),
('George Jean Nathan'),
('Ring Lardner'),
('Larry Prentiss'),
('William Ralph Inge'),
('Bernard Fall'),
('Dat Tran'),
('Eric Fenstermaker'),
('Matt Wall'),
('Seneca'),
('Henry Adams'),
('Edward Taylor, Somerdale, N.J.'),
('Mary Wilson Little'),
('Della Stowers'),
('Elsa Maxwell'),
('Horace Greeley McNabb'),
('Hon. John E. Powers'),
('Duke Ellington'),
('Hannes Kling, Leucadia, Calif.'),
('Wystan Hugh Auden'),
('Rhama B. Cubbage'),
('Mark Meggison, China Groves, N.C.'),
('Charles E. McCandless'),
('Greg Ward, Laurel, Neb'),
('Hebrew Proverb'),
('Adapted from G.K. Chesterton'),
('Duane Grasse, Arton, wyo.'),
('saying credited to Chinese laundrymen'),
('Cincinnati Enquirer'),
('Chris Duffield, Bakersfield, CA'),
('John Dos Passos'),
('Ernst von Freuchtersleben'),
('1'),
('Anbrose Bierce'),
('James Harvey Robinson'),
('Arthur Schopenhauer'),
('Madeleine de ScudŽry'),
('Richard Kinney'),
('Katherine Mansfield'),
('Max Eastman'),
('Heywood Brown'),
('Tom Masson'),
('Eugene Debs'),
('John D. Rockefeller'),
('J.P. Morgan'),
('Anne Morrow Lindbergh'),
('Bob Hope'),
('Shelby Friedman'),
('Mary Ann Madden'),
('Dick O\'Connell'),
('Tom Kane, Hicksville, N.H.'),
('Jess Rosen'),
('Eleonora Duse'),
('William Hazzitt'),
('Charles Dudley Warner'),
('Henry Brooks Adams'),
('David Person, Houston, TX'),
('Carl Sandburg'),
('James Stephens'),
('Mary Trank'),
('Dan Kidney'),
('Teresa Benstead'),
('Solon (c.638-c.559 B.C.)'),
('Richard Lannelli'),
('Herold Poole'),
('Martha L. Creager'),
('Michael H. Wilson'),
('Peter Keyes'),
('Ray Dean Davis'),
('Irv Cohen'),
('American Proverb'),
('Paul Sweeney'),
('Disraeli'),
('Marion L. Justice'),
('John K. Young'),
('Penelope Gilliatt'),
('Frank McKinney Hubbard'),
('Edmund Burke'),
('Deborah Love'),
('Justin Swapp, Juneau, Alaska'),
('Mrs. Deane Binder'),
('Joseph Joubert'),
('Mary Little Wilson'),
('Mignon McLaughlin'),
('Matthew Trotta, Easley, S.C.'),
('Matthew Hamblin, Roosevelt, Utah'),
('Michael Burridge, Palatka, Fla.'),
('G.H. Ebbert'),
('A.H. Berzen'),
('John M. Steinbach'),
('Brad Gladfelter, Kewanee, Ill.'),
('Alcaeus'),
('Dennis DeYoung'),
('Hannah Cowley'),
('Aeschylus'),
('Horace Walpole'),
('Arthur Somers Roche'),
('Maude Peterson'),
('William Ralph (Dean) Inge'),
('Sam Levenson'),
('Kevin Harris, Tacoma, Wash.'),
('Leonard Klein'),
('Paul R. Schneider');